[theme]
primaryColor = "#E2001A"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#1A1A1A"
font = "sans serif"

[ui]
hideTopBar = false

[client]
showSidebarNavigation = false
